Add go ldflags using LDFLAGS at the time of compilation
kubernetes-csi/external-attacher pull request #265
Opened 2020-10-16 17:26 UTC by bnrjee

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR allows adding ldflags while running make. We are trying build a binary without debug info. With this change we will be able to pass -s flag as an argument to Makefile.

**Which issue(s) this PR fixes**:

Fixes #264

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2020-10-16 17:47 UTC, bnrjee commented
Tests performed,
1>Made sure that the build is without debug info and repeatable. 

```
[root@ip-172-31-13-77 external-attacher]# make BUILD_PLATFORMS="linux arm64" LDFLAGS="-s -w -buildid=''"
./release-tools/verify-go-version.sh "go"
mkdir -p bin
echo 'linux arm64' | tr ';' '\n' | while read -r os arch suffix; do \
	if ! (set -x; CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build  -a -ldflags '-s -w -buildid='' -X main.version=v3.0.0-15-geb0627a8 -extldflags "-static"' -o "./bin/csi-attacher$suffix" ./cmd/csi-attacher); then \
		echo "Building csi-attacher for GOOS=$os GOARCH=$arch failed, see error(s) above."; \
		exit 1; \
	fi; \
done
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=arm64
+ go build -a -ldflags '-s -w -buildid= -X main.version=v3.0.0-15-geb0627a8 -extldflags "-static"' -o ./bin/csi-attacher ./cmd/csi-attacher
[root@ip-172-31-13-77 external-attacher]# file bin/csi-attacher 
bin/csi-attacher: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
[root@ip-172-31-13-77 external-attacher]# sha256sum bin/csi-attacher 
15403c34dbdab0d9931feae2da04789c53e92f2be8c2a63487e1dd031db702b9  bin/csi-attacher
[root@ip-172-31-13-77 external-attacher]# make clean
rm -rf bin
[root@ip-172-31-13-77 external-attacher]# make BUILD_PLATFORMS="linux arm64" LDFLAGS="-s -w -buildid=''"
./release-tools/verify-go-version.sh "go"
mkdir -p bin
echo 'linux arm64' | tr ';' '\n' | while read -r os arch suffix; do \
	if ! (set -x; CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build  -a -ldflags '-s -w -buildid='' -X main.version=v3.0.0-15-geb0627a8 -extldflags "-static"' -o "./bin/csi-attacher$suffix" ./cmd/csi-attacher); then \
		echo "Building csi-attacher for GOOS=$os GOARCH=$arch failed, see error(s) above."; \
		exit 1; \
	fi; \
done
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=arm64
+ go build -a -ldflags '-s -w -buildid= -X main.version=v3.0.0-15-geb0627a8 -extldflags "-static"' -o ./bin/csi-attacher ./cmd/csi-attacher
[root@ip-172-31-13-77 external-attacher]# file bin/csi-attacher 
bin/csi-attacher: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
[root@ip-172-31-13-77 external-attacher]# sha256sum bin/csi-attacher 
15403c34dbdab0d9931feae2da04789c53e92f2be8c2a63487e1dd031db702b9  bin/csi-attacher
[root@ip-172-31-13-77 external-attacher]# 
```

2020-10-16 18:10 UTC, micahhausler requested changes

2020-10-16 18:10 UTC, micahhausler commented on release-tools/build.make
> +LDFLAGS =
Consumers still couldn't override `-extldflags`, maybe set this to 
```suggestion
LDFLAGS ?= -X main.version=$(REV) -extldflags "-static"
```

2020-10-16 18:10 UTC, micahhausler commented on release-tools/build.make
> +		if ! (set -x; CGO_ENABLED=0 GOOS="$$os" GOARCH="$$arch" go build $(GOFLAGS_VENDOR) -a -ldflags '$(LDFLAGS) -X main.version=$(REV) -extldflags "-static"' -o "./bin/$*$$suffix" ./cmd/$*); then \
```suggestion
		if ! (set -x; CGO_ENABLED=0 GOOS="$$os" GOARCH="$$arch" go build $(GOFLAGS_VENDOR) -a -ldflags '$(LDFLAGS)' -o "./bin/$*$$suffix" ./cmd/$*); then \
```

2020-10-19 11:10 UTC, jsafrane commented
@bnrjee, please submit a PR against https://github.com/kubernetes-csi/csi-release-tools, content of `release-tools/` is copied from there. And it will fix all other CSI repos too.

2020-10-19 18:24 UTC, bnrjee commented
> @bnrjee, please submit a PR against https://github.com/kubernetes-csi/csi-release-tools, content of `release-tools/` is copied from there. And it will fix all other CSI repos too.

I have created this PR
https://github.com/kubernetes-csi/csi-release-tools/pull/108

2020-10-27 19:16 UTC, pohly commented
/close

Merged via csi-release-tools.

2020-10-27 19:16 UTC, closed without merging